function ApplicationTabGroup(){Ti.API.info("Create Tabgroup");require("ui/handheld/ApplicationWindow");require("ui/winmodule/WebViewWindow");require("ui/winmodule/WebVideoWindow");require("ui/winmodule/ImageViewWindow");require("ui/winmodule/ContactWindow");require("ui/winmodule/TableViewWindow");require("ui/winmodule/AccountWindow");require("ui/winmodule/QRAccountWindow");require("ui/winmodule/RSSWindow");require("ui/winmodule/RSSWindow2");require("ui/winmodule/CustomPageWindow");require("ui/winmodule/ChatWindow");
var b=Ti.UI.createTabGroup(),g=[],j=[],l=Ti.App.Properties.getString("cloud_useremail","viewer.defaultui@fuihan.com"),m=Ti.App.Properties.getString("cloud_userpassword","viewerInPub"),k=function(){Ti.API.info("loadingTabs Tabgroup");var a=require("ti.cloud");a.Users.login({login:l,password:m},function(e){e.success?(e=e.users[0],Ti.API.info("Step 1 - Login Success, Start Querying"),""!=Ti.App.Properties.getString("cloud_useremail","")&&Ti.App.Properties.setBool("cloud_Logged",!0),"viewer.defaultui@fuihan.com"==
e.email&&Ti.App.Properties.setString("chat_root_user",e.id),a.Objects.query({classname:"windows",page:1,per_page:30,order:"win_id",where:{user_id:e.custom_fields.content_user_id,win_id:{$gt:0},win_root_id:0}},function(a){if(a.success){Ti.API.info("Step 2 - Qureying Results Received : "+a.windows.length+" Windows ");g=[];for(var e=require("ui/winmodule/WindowRouter"),n=0,h=0;h<a.windows.length;h++){var c=a.windows[h];Ti.API.info("Step 2+ - Qureying Results Received : Window "+h+" Type - "+c.win_type);
Ti.API.info("ACL:"+c.win_published);if("undefined"==typeof c.win_published||c.win_published)if(Ti.API.info("Step 2+ - processing Results Received : Window "+h+" Type - "+c.win_type),"mobileweb"!=Ti.Platform.osname||"mobileweb"==Ti.Platform.osname&&"TYPE_QRACCOUNT"!=c.win_type){switch(c.win_type){case "TYPE_TABLE":var d=[];d.push(c.win_parameters[0]);d.push(c.win_parameters[1]);d.push(c.win_parameters[2]);d.push(c.win_id);d.push(0);d=new e(c.win_type,d,c.id);break;default:d=new e(c.win_type,c.win_parameters,
c.id)}var f=c.win_icon?c.win_icon:"about",i=Ti.UI.createTab({title:c.win_title,icon:"/icons/"+f+".png",window_type:c.win_type,window:d});"android"==Ti.Platform.osname&&"TYPE_QRACCOUNT"==c.win_type&&(i.title="mCMS");i.icon="mobileweb"==Ti.Platform.osname?"http://mcms.fuihan.com/mobileWeb/icons/"+f+".png":"/icons/"+f+".png";d.containingTab=i;d._tabcount=a.windows.length;d.addEventListener("ReloadTabs",function(){Ti.API.info("Step 3 - ReloadTabs Start");Ti.API.info("Clear  - self_win.tabs.length:"+b.tabs.length);
b.animate({opacity:0,duration:200},function(){if("android"==Ti.Platform.osname)require("com.nametec.reboot").reboot();else{for(var a=b.tabs.length-1;0<a;a--)Ti.API.info("Clear  - var j:"+a),b.removeTab(b.tabs[a]);k(b)}})});d.addEventListener("switch2Tabs",function(){Ti.API.info("Step 3+ - Switch to selected Tab");b.fireEvent("1switch2Tabs")});g[n]=i;n++}}for(a=0;a<g.length;a++)Ti.API.info("Add  - resultTabs:"+a),b.addTab(g[a]);j=g;g.length<b.tabs.length&&b.removeTab(b.tabs[0]);b.activeTab=0}else alert("Sorry, Failed in getting Contents withi your account, Please check your content managements.");
b.animate({opacity:1,duration:300},function(){})})):alert("Sorry, Failed in Loggin in. Please try again later.");Ti.API.info("Step 5 - Query Done")});Ti.API.info("Step 6 - Login Done")};if(""!=Ti.App.Properties.getString("cloud_useremail","")||"mobileweb"==Ti.Platform.osname)"mobileweb"==Ti.Platform.osname&&(l="viewer."+Ti.Utils.base64decode(Ti.App.Properties.getString("viewerid","")).toString().toString().substr(9,200),m="viewerInPub"),k(b);else{var g=[],a=require("ui/winmodule/WindowRouter");if("mobileweb"==
Ti.Platform.osname)var a=new a("TYPE_WIN",[!0,!0,"Welcome to mCMS",""],""),f=Ti.UI.createTab({title:"Welcome to mCMS",icon:"/icons/info.png",window_type:"TYPE_WIN",window:a});else a=new a("TYPE_QRACCOUNT",["Scan Your QR Codes"],""),f=Ti.UI.createTab({title:"Scan Your QR Codes",icon:"/icons/qrcode.png",window_type:"TYPE_QRACCOUNT",window:a}),"android"==Ti.Platform.osname&&(f.title="mCMS");a.containingTab=f;a._tabcount=0;a.addEventListener("ReloadTabs",function(){b.animate({opacity:0,duration:200},
function(){"android"==Ti.Platform.osname?require("com.nametec.reboot").reboot():k(b)})});a.addEventListener("switch2Tabs",function(){b.fireEvent("1switch2Tabs")});b.addTab(f);b.activeTab=0}b.fireEvent("ClearTabs",function(){Ti.API.info("Step 3++ - ClearTabs");for(var a=0;a<j.length;a++)Ti.API.info("Clear  - builttabs:"+a),b.removeTab(j[a])});b.addEventListener("1switch2Tabs",function(){Ti.API.info("Step 3++ - 1switch2Tabs");b.activeTab=2<=b.tabs.length&&"TYPE_QRACCOUNT"!=b.tabs[0].window_type||2>
b.tabs.length&&"TYPE_QRACCOUNT"==b.tabs[0].window_type?0:1});return b}module.exports=ApplicationTabGroup;