function ChatWindow(l,m,j,b){if("android"!=Ti.Platform.osname){var h=require("ti.cloud"),d,k,l=require("ti.smsview"),m=Ti.UI.createButtonBar({labels:["Recieve","Empty","Get All","Disable","Enable"],height:30,style:Ti.UI.iPhone.SystemButtonStyle.BAR});Ti.UI.createView().add(m);var j=Ti.UI.createWindow({orientationModes:[1,2,3,4]}),c=l.createView({backgroundColor:"#dae1eb",returnType:l.RETURNKEY_DONE,camButton:!0,hasTab:!0});j.add(c);m.addEventListener("click",function(a){switch(a.index){case 0:c.recieveMessage("Hello World!");
break;case 1:c.empty();break;case 2:Ti.API.info(c.getAllMessages());break;case 3:c.sendButtonDisabled=!0;break;case 4:c.sendButtonDisabled=!1}});c.addEventListener("click",function(a){a.scrollView&&c.blur();Ti.API.info("Clicked on the scrollview")});c.addEventListener("buttonClicked",function(a){var g=[],n=Ti.App.Properties.getString("chat_root_user","");g.push(b);""!=n&&g.push(n);d.id!=n&&d.id!=b&&g.push(d.id);h.Chats.create({to_ids:g.join(","),message:"Say: "+a.value},function(a){if(a.success)for(var e=
0;e<a.chats.length;e++){var f=a.chats[e],o=f.chat_group.participate_users;c.sendMessage(f.message+"/Group:"+f.chat_group.id+"/Users:"+o.length+"/ID:"+o[0].id+" /"+o[1].id);k=f.created_at}else alert("Error:\\n"+(a.error&&a.message||JSON.stringify(a)))})});c.addEventListener("camButtonClicked",function(){var a=Ti.UI.createOptionDialog({options:["Photo Gallery","Cancel"],cancel:1,title:"Send a photo"});a.show();a.addEventListener("click",function(a){0==a.index&&Titanium.Media.openPhotoGallery({success:function(a){h.Photos.create({photo:a.media,
photo_sync_sizes:"small_240"},function(a){if(a.success){var e=a.photos[0],a=[],f=Ti.App.Properties.getString("chat_root_user","");a.push(b);""!=f&&a.push(f);d.id!=f&&d.id!=b&&a.push(d.id);alert(a.length+":"+a.join(","));h.Chats.create({to_ids:a.join(","),message:"sendImage:"+e.id},function(a){if(a.success){var a=a.chats[i],f=Ti.UI.createImageView({image:e.urls.small_240});c.sendMessage(f.toBlob());k=a.created_at}else alert("Error:\\n"+(a.error&&a.message||JSON.stringify(a)))})}else alert("Error:\\n"+
(a.error&&a.message||JSON.stringify(a)))})},mediaTypes:[Ti.Media.MEDIA_TYPE_PHOTO]})})});c.addEventListener("messageClicked",function(a){a.text&&Ti.API.info("Text: "+a.text);a.image&&Ti.API.info("Image: "+a.image);Ti.API.info("Index: "+a.index)});j.addEventListener("open",function(){h.Users.login({login:Ti.App.Properties.getString("cloud_useremail","defaultui@fuihan.com"),password:Ti.App.Properties.getString("cloud_userpassword","fuihan168")},function(a){if(a.success){d=a.users[0];var a=[],g=Ti.App.Properties.getString("chat_root_user",
"");a.push(b);""!=g&&a.push(g);d.id!=g&&d.id!=b&&a.push(d.id);alert(a.length+":"+a.join(","));h.Chats.query({participate_ids:a.join(","),limit:100,where:{created_at:{$gte:"2012-01-01T22:53:48+0000"}}},function(a){if(a.success)for(var b=0;b<a.chats.length;b++){var e=a.chats[b];e.from.id==d.id?"sendImage:"==e.message.substring(0,10)?h.Photos.show({photo_id:e.message.substring(10)},function(a){a.success?(a=Ti.UI.createImageView({image:a.photos[0].urls.small_240}),c.sendMessage(a.toBlob())):alert("Error:\\n"+
(a.error&&a.message||JSON.stringify(a)))}):c.sendMessage(e.message):"sendImage:"==e.message.substring(0,10)?h.Photos.show({photo_id:e.message.substring(10)},function(a){a.success?(a=Ti.UI.createImageView({image:a.photos[0].urls.small_240}),c.recieveMessage(a.toBlob())):alert("Error:\\n"+(a.error&&a.message||JSON.stringify(a)))}):c.recieveMessage(e.message);k=e.created_at}else alert("Error:\\n"+(a.error&&a.message||JSON.stringify(a)))});setInterval(function(){var a=[],g=Ti.App.Properties.getString("chat_root_user",
"");a.push(b);""!=g&&a.push(g);d.id!=g&&d.id!=b&&a.push(d.id);h.Chats.query({participate_ids:a.join(","),where:{created_at:{$gt:k}}},function(a){if(a.success)for(var f=0;f<a.chats.length;f++){var b=a.chats[f];b.from.id==d.id?"sendImage:"==b.message.substring(0,10)?h.Photos.show({photo_id:b.message.substring(10)},function(a){a.success?(a=Ti.UI.createImageView({image:a.photos[0].urls.small_240}),c.sendMessage(a.toBlob())):alert("Error:\\n"+(a.error&&a.message||JSON.stringify(a)))}):c.sendMessage(b.message):
"sendImage:"==b.message.substring(0,10)?h.Photos.show({photo_id:b.message.substring(10)},function(a){a.success?(a=Ti.UI.createImageView({image:a.photos[0].urls.small_240}),c.recieveMessage(a.toBlob())):alert("Error:\\n"+(a.error&&a.message||JSON.stringify(a)))}):c.recieveMessage(b.message);k=b.created_at}else alert("Error:\\n"+(a.error&&a.message||JSON.stringify(a)))})},3E4)}else alert("Error:\\n"+(a.error&&a.message||JSON.stringify(a)))})})}else j=Ti.UI.createWindow({orientationModes:[1,2,3,4]}),
Ti.UI.createLabel({text:"Sorry, Chatting on Android is still in development, sorry for the inconvience.",font:{fontSize:18}});j.navBarHidden=!0;return j}module.exports=ChatWindow;